### ISSUE TITLE
Add test utility for generating a random object

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.JavaScript.Testing#12]
There have been a few cases where we've needed to generate an object with random keys & values. Usually this involves creating an empty object, looping a certain number of times, and indexing into the object by a random string to assign some value.

An example implementation might look something like this - 

```TS
function randomObject(keyCount?: number) {
    const randomObject = {};
    if (keyCount == null || keyCount <= 0) {
        keyCount = this.randomNumber(1, 10);
    }

    while (Object.keys(randomObject).length < keyCount) {
        const key = faker.random.uuid();
        if (randomObject[key] != null) {
            continue;
        }
        randomObject[key] = this.randomNumber();
    }

    return randomObject;
}
```

**Comment by vansosnin** [comment]
I can do it. Will try to complete today
