### ISSUE TITLE
Add test utility to pick a random property off of an object

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.JavaScript.Testing#2]
To improve test data randomization there are various scenarios where you might want to grab a random property value off of an object. Say an object of string constants.

Implementation for this could be based upon...

```javascript
const randomProperty = (obj) => {
    const keys = Object.keys(obj);
    const index = keys.length * Math.random() << 0;
    return obj[keys[index]];
};
```

**Comment by brandongregoryscott** [comment]
Published with [v0.0.3](https://github.com/AndcultureCode/AndcultureCode.JavaScript.Testing/releases/tag/v0.0.3)
