### ISSUE TITLE
Add test utility function for generating a random path

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.JavaScript.Testing#8]
Faker does not seem to have a path generating function implemented yet, so we rolled one in AndcultureCode.Cli - see https://github.com/AndcultureCode/AndcultureCode.Cli/blob/master/tests/test-utils.js#L283 for reference

*Note* One update to this implementation that would probably be nice is actually randomizing the number of "paths" deep that it generates - right now, the `maxDepth` parameter is misleading (it will always generate a 'path' of that depth)

Add this function plus any applicable unit tests

**Comment by vansosnin** [comment]
I can take it after merging #14 to avoid conflicts

**Comment by brandongregoryscott** [comment]
After a recent discovery in #13, it seems that faker might actually have this available now. We can probably just forward that function if it's actually returning a value, but double check it 👍

**Comment by vansosnin** [comment]
faker does not receive depth argument. Is it okay?

**Comment by brandongregoryscott** [comment]
That's fine @vansosnin 👍 In all honestly, I was thinking it might be a 'nice-to-have', but I don't think it was used.
